### ISSUE TITLE
Turn camera green LED ring on and off

### ISSUE THREAD

**Issue by JohnRudolfLewis** [FRC-1294/frc2018#12]
VisionSubsystem.setCameraNormal and VisionSubsystem.setCameraForVisionTarget have todo comments to turn the green led ring on and off.

**Comment by timtim17** [comment]
Green LED ring was destroyed by bad placement and arm actuation (crushed by something iirc?). Vision ultimately not used, closing for now. Could possibly pursue vision and other more interesting things over summer for offseasons...
