### ISSUE TITLE
Tune DriveStraightCommand Forward PID

### ISSUE THREAD

**Issue by JohnRudolfLewis** [FRC-1294/frc2018#17]
1. add distance over time graph on the smart dashboard
2. add code to allow tuning of PID parameters from smart dashboard
4. add button to smart dashboard to drive forward a particular distance
5. set pid parameters, p to a reasonable starting guess of 0.1, i and d to 0
6. press the smart dashboard button, observe the graph
7. look for continuous oscillation... amplitude and frequency stable
9. until you see continuous oscillation, increase the P constant, repeat above three steps
10. once you see continuous oscillation, record Ku and Tu 
Ku = the ultimate gain = the P value you used above
Tu = oscilation period = the peak to peak time observed above)
11. Choose a control type and do the maths from https://en.wikipedia.org/wiki/Ziegler%E2%80%93Nichols_method or use https://docs.google.com/spreadsheets/d/1qDopKCobqPzRtl3etobEXdA41mcEHj6qkPq0o_CFZwY/edit?usp=sharing
12. Try out the P, I, D values you came up with and observe the behavior of the graph when pressing and releasing the various speed buttons.
13. Repeat until satisfied

**Comment by timtim17** [comment]
Closed for a similar reason as #18. The tuning isn't perfect, as only combinations of "fast speed long distance" and "slow speed short distance" work (preferably we'd have "fast speed short distance"), but it works well enough for now.
