### ISSUE TITLE
Tune DriveStraightCommand Turn PID

### ISSUE THREAD

**Issue by JohnRudolfLewis** [FRC-1294/frc2018#18]
1. add heading over time graph on the smart dashboard
2. add code to allow tuning of PID parameters from smart dashboard
3. add commands that set desired heading to 0, 90, 180, 270 on the smart dashboard
4. press one of the buttons, observe the graph
5. look for continuous oscillation... amplitude and frequency stable
6. until you see continuous oscillation, increase the P constant, repeat above three steps
7. once you see continuous oscillation, record Ku and Tu 
Ku = the ultimate gain = the P value you used above
Tu = oscilation period = the peak to peak time observed above)
8. Choose a control type and do the maths from https://en.wikipedia.org/wiki/Ziegler%E2%80%93Nichols_method or use https://docs.google.com/spreadsheets/d/1qDopKCobqPzRtl3etobEXdA41mcEHj6qkPq0o_CFZwY/edit?usp=sharing
9. Try out the P, I, D values you came up with and observe the behavior of the graph when pressing various heading buttons.
10. Repeat until satisfied

**Comment by timtim17** [comment]
Tuned mostly well enough for now. Still a little bit of overshoot, and finishes a little slower than preferable, but good enough, especially at where we are now in the season.
