### ISSUE TITLE
Arm

### ISSUE THREAD

**Issue by klundblad** [FRC-1294/frc2018#20]
One controller Y axis, Two Buttons for moving pre-set positions, 1 CIM, Linear Pot (Need to limit arm travel up and down and need to go to pre-set position)

**Comment by timtim17** [comment]
- [X] one controller y axis
- [x] presets
  - [x] talon position pid tuning
- [X] CIM
- [X] Linear Pot
- [X] Soft limits
  - [ ] TODO: Set limits in code. Check robot for updated numbers.

**Comment by timtim17** [comment]
The arm works "well enough" for what we have. Could probably use motion profiling/motion magic over the summer for offseasons, but it looks like we're rebuilding a few things over the summer anyways, so for now 🤷‍♂️.
