### ISSUE TITLE
Cube Handler

### ISSUE THREAD

**Issue by klundblad** [FRC-1294/frc2018#21]
One controller Y axis (Cube in and out) (Stop Cube in when cube is engaged), One controller Y axis (Wrist rotate up and down), Button to move to pre-set position, Light to indicate when cube is engaged

**Comment by timtim17** [comment]
- [x] One controller _triggers_
- [ ] stop cube when engaged
  - no sensor
- [x] wrist motion on _d-pad_
  - [ ] presets
- [ ] light to indicate when cube is engaged/*when we want the human player to drop a cube*
  - alliance leds broken (switch)
  - green camera leds broken (wires)
  - fancy leds don't exist (arduino)
  - options:
    - Shuffleboard dashboard indicator (boring)
      - `while` we have the cube alternate a `SmartDashboard.putBoolean` on and off to make it flash
    - green leds on a spark (small and unoticeable, but the spark is already there)
    - fancy/normal led strips
      - probably just feed a DIO output from the RIO to the LEDs somehow... power LEDs from the RIO? control what alliance color they are with `DriverStation.getInstance().getAllianceColor()` (or whatever it's called)?
      - more noticeable and cool
      - could use an arduino to fade it down/animate

**Comment by heatblast016** [comment]
Will try and get presets set up for arm. Need sensor values for encoder. Talon Motion Magic will smooth motion, however we need to keep within 16 in. Possible solution: keep sliding in/out unless it is above 16 in. Problems with that: linear pot doesn't help us out with getting distance. Any Ideas?

**Comment by timtim17** [comment]
Basically done. We don't have an LED ring anymore (broken iirc?). Not even priority anyways, so intake's good for now. Closing issue for posterity.
